In [ ]:
#Import Library
import pandas as pd
import numpy as np
import random

#Buat Data Kotor
random.seed(42)

names = [
    "Andi","Budi","Citra","Dewi","Eko","Farhan","Gita","Hendra",
    "Indah","Joko","Kiki","Lina","Maya","Nina","Oscar","Putri",
    "Rina","Sinta","Tono","Wawan"
]

cities = [
    "Jakarta","Bandung","Surabaya","Semarang","Medan",
    "Yogyakarta","Malang","Denpasar"
]

gender = [
    "M","Male","L","Laki-laki",
    "F","Female","P","Perempuan"
]

rows = []

for i in range(100):

    name = random.choice(names)

    # Nama dibuat tidak konsisten
    if random.random() < 0.2:
        name = name.upper()
    elif random.random() < 0.2:
        name = name.lower()

    if random.random() < 0.15:
        name = " " + name + " "

    age = random.choice([
        random.randint(20,55),
        "",
        None,
        -5,
        150
    ])

    city = random.choice(cities)

    if random.random() < 0.2:
        city = city.lower()

    salary = random.choice([
        random.randint(4000000,15000000),
        f"Rp {random.randint(4,15)}.000.000",
        f"{random.randint(4,15)},000,000",
        "",
        None
    ])

    join_date = random.choice([
        "2024-01-10",
        "10/01/2024",
        "Jan 10 2024",
        "2024/01/10",
        ""
    ])

    gender_value = random.choice(gender)

    rows.append([
        i+1,
        name,
        age,
        gender_value,
        city,
        salary,
        join_date
    ])

# Tambahkan duplikasi
rows.append(rows[5])
rows.append(rows[20])
rows.append(rows[35])

df = pd.DataFrame(rows, columns=[
    "ID",
    "Name",
    "Age",
    "Gender",
    "City",
    "Salary",
    "JoinDate"
])

#hasil Data Kotor
print(df)

df.to_csv("dirty_employee_data.csv", index=False)

      ID     Name  Age     Gender        City         Salary     JoinDate
0      1     DEWI               M     Bandung                  2024-01-10
1      2   Citra   150     Female      Malang   Rp 8.000.000   2024/01/10
2      3    INDAH   41  Perempuan     Bandung     13,000,000   2024-01-10
3      4    SINTA  150          M       Medan   Rp 9.000.000   2024-01-10
4      5   Hendra   -5          F       Medan      9,000,000   10/01/2024
..   ...      ...  ...        ...         ...            ...          ...
98    99     Tono   38       Male      malang                 Jan 10 2024
99   100     Nina   53       Male      Malang   Rp 7.000.000   2024-01-10
100    6    citra   -5          M      Malang  Rp 15.000.000  Jan 10 2024
101   21     Nina          Female  Yogyakarta     14,000,000   2024/01/10
102   36    Budi    -5  Perempuan  Yogyakarta           None   2024/01/10

[103 rows x 7 columns]

In [ ]:
#Tampilan Data Kotor
df

      ID     Name  Age     Gender        City         Salary     JoinDate
0      1     DEWI               M     Bandung                  2024-01-10
1      2   Citra   150     Female      Malang   Rp 8.000.000   2024/01/10
2      3    INDAH   41  Perempuan     Bandung     13,000,000   2024-01-10
3      4    SINTA  150          M       Medan   Rp 9.000.000   2024-01-10
4      5   Hendra   -5          F       Medan      9,000,000   10/01/2024
..   ...      ...  ...        ...         ...            ...          ...
98    99     Tono   38       Male      malang                 Jan 10 2024
99   100     Nina   53       Male      Malang   Rp 7.000.000   2024-01-10
100    6    citra   -5          M      Malang  Rp 15.000.000  Jan 10 2024
101   21     Nina          Female  Yogyakarta     14,000,000   2024/01/10
102   36    Budi    -5  Perempuan  Yogyakarta           None   2024/01/10

[103 rows x 7 columns]

In [ ]:
#Info Data Kotor
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        103 non-null    int64
 1   Name      103 non-null    object
 2   Age       84 non-null     object
 3   Gender    103 non-null    object
 4   City      103 non-null    object
 5   Salary    86 non-null     object
 6   JoinDate  103 non-null    object
dtypes: int64(1), object(6)
memory usage: 5.8+ KB

In [ ]:
#unique value data gaji
df['Salary'].unique()

array(['', 'Rp 8.000.000', '13,000,000', 'Rp 9.000.000', '9,000,000',
       'Rp 15.000.000', 6320821, None, '5,000,000', '6,000,000',
       'Rp 11.000.000', 4987737, 11935169, 'Rp 7.000.000', 'Rp 4.000.000',
       '14,000,000', 5737893, 'Rp 5.000.000', 7524499, 'Rp 10.000.000',
       13673542, 9539837, 'Rp 12.000.000', '10,000,000', 13658481,
       8579094, 14187922, 'Rp 6.000.000', '15,000,000', 13103209,
       11350368, '11,000,000', 'Rp 14.000.000', '4,000,000', 4485654,
       'Rp 13.000.000', '8,000,000', 7991829, 10074006, 13421856, 6610197,
       8286905], dtype=object)

In [ ]:
#Handle standardisasi Type Data

#Age
df['Age']=df['Age'].replace('',np.nan)
df['Age']=df['Age'].replace(-5,np.nan)
df['Age']=df['Age'].astype('Int64')

#Salary
df['Salary']=df['Salary'].astype(str)
df['Salary']=df['Salary'].replace('',np.nan)
df['Salary']=df['Salary'].str.replace('Rp','')
df['Salary']=df['Salary'].str.replace('.','', regex=False)
df['Salary']=df['Salary'].str.replace(',','', regex=False)
df['Salary']=df['Salary'].str.replace(' ','', regex=False)
df['Salary']=df['Salary'].str.replace('-','', regex=False)

# Use pd.to_numeric with errors='coerce' to convert non-numeric values (including '') to NaN
df['Salary']=pd.to_numeric(df['Salary'],errors='coerce')
df['Salary']=df['Salary'].astype('Int64')

#JoinDate
df['JoinDate']=df['JoinDate'].astype(str)
df['JoinDate']=df['JoinDate'].replace('',np.nan)
df['JoinDate']=df['JoinDate'].str.replace('/','-')
df['JoinDate']=df['JoinDate'].str.replace('Jan','01')
df['JoinDate']=df['JoinDate'].str.replace(' ','-')
df['JoinDate']=pd.to_datetime(df['JoinDate'],errors='coerce',dayfirst=True)

/tmp/ipykernel_1236/1436432313.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Age']=df['Age'].replace('',np.nan)

In [ ]:
df['JoinDate'].unique()

<DatetimeArray>
['2024-10-01 00:00:00', 'NaT']
Length: 2, dtype: datetime64[ns]

In [ ]:
df

      ID     Name   Age     Gender        City    Salary   JoinDate
0      1     DEWI  <NA>          M     Bandung      <NA> 2024-10-01
1      2   Citra    150     Female      Malang   8000000 2024-10-01
2      3    INDAH    41  Perempuan     Bandung  13000000 2024-10-01
3      4    SINTA   150          M       Medan   9000000 2024-10-01
4      5   Hendra  <NA>          F       Medan   9000000        NaT
..   ...      ...   ...        ...         ...       ...        ...
98    99     Tono    38       Male      malang      <NA>        NaT
99   100     Nina    53       Male      Malang   7000000 2024-10-01
100    6    citra  <NA>          M      Malang  15000000        NaT
101   21     Nina  <NA>     Female  Yogyakarta  14000000 2024-10-01
102   36    Budi   <NA>  Perempuan  Yogyakarta      <NA> 2024-10-01

[103 rows x 7 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        103 non-null    int64
 1   Name      103 non-null    object
 2   Age       44 non-null     Int64
 3   Gender    103 non-null    object
 4   City      103 non-null    object
 5   Salary    69 non-null     Int64
 6   JoinDate  51 non-null     datetime64[ns]
dtypes: Int64(2), datetime64[ns](1), int64(1), object(3)
memory usage: 6.0+ KB

In [ ]:
#Tampilan Unique Value Age
df['Age'].unique()

<IntegerArray>
[<NA>, 150, 41, 51, 34, 26, 53, 54, 43, 55, 39, 31, 29, 28, 49, 27, 47, 45,
 38]
Length: 19, dtype: Int64

In [ ]:
#Handle Missing Value
df['Age']=df['Age'].fillna(df['Age'].mean().astype(int))
df['Salary']=df['Salary'].fillna(df['Salary'].mean().astype(int))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        103 non-null    int64
 1   Name      103 non-null    object
 2   Age       103 non-null    Int64
 3   Gender    103 non-null    object
 4   City      103 non-null    object
 5   Salary    103 non-null    Int64
 6   JoinDate  51 non-null     datetime64[ns]
dtypes: Int64(2), datetime64[ns](1), int64(1), object(3)
memory usage: 6.0+ KB

In [ ]:
#Handle Missing Value JoinDate dengan Modus
df['JoinDate']=df['JoinDate'].fillna(df['JoinDate'].mode()[0])

In [ ]:
#Handle Missing Value Done
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        103 non-null    int64
 1   Name      103 non-null    object
 2   Age       103 non-null    Int64
 3   Gender    103 non-null    object
 4   City      103 non-null    object
 5   Salary    103 non-null    Int64
 6   JoinDate  103 non-null    datetime64[ns]
dtypes: Int64(2), datetime64[ns](1), int64(1), object(3)
memory usage: 6.0+ KB

In [ ]:
df

      ID     Name  Age     Gender        City    Salary   JoinDate
0      1     DEWI   86          M     Bandung   9412594 2024-10-01
1      2   Citra   150     Female      Malang   8000000 2024-10-01
2      3    INDAH   41  Perempuan     Bandung  13000000 2024-10-01
3      4    SINTA  150          M       Medan   9000000 2024-10-01
4      5   Hendra   86          F       Medan   9000000 2024-10-01
..   ...      ...  ...        ...         ...       ...        ...
98    99     Tono   38       Male      malang   9412594 2024-10-01
99   100     Nina   53       Male      Malang   7000000 2024-10-01
100    6    citra   86          M      Malang  15000000 2024-10-01
101   21     Nina   86     Female  Yogyakarta  14000000 2024-10-01
102   36    Budi    86  Perempuan  Yogyakarta   9412594 2024-10-01

[103 rows x 7 columns]

In [ ]:
#Handle kolom Name, Gender, City
df['Name']=df['Name'].str.lower().str.strip().str.title()
df['Gender']=df['Gender'].str.lower().str.strip().map({'m':'Laki-Laki','l':'Laki-Laki','male':'Laki-Laki',
                                                       'f':'Perempuan','p':'Perempuan','female':'Perempuan',
                                                       'laki-laki':'Laki-Laki','perempuan':'Perempuan'})
df['City']=df['City'].str.lower().str.strip().str.title()
df

      ID    Name  Age     Gender        City    Salary   JoinDate
0      1    Dewi   86  Laki-Laki     Bandung   9412594 2024-10-01
1      2   Citra  150  Perempuan      Malang   8000000 2024-10-01
2      3   Indah   41  Perempuan     Bandung  13000000 2024-10-01
3      4   Sinta  150  Laki-Laki       Medan   9000000 2024-10-01
4      5  Hendra   86  Perempuan       Medan   9000000 2024-10-01
..   ...     ...  ...        ...         ...       ...        ...
98    99    Tono   38  Laki-Laki      Malang   9412594 2024-10-01
99   100    Nina   53  Laki-Laki      Malang   7000000 2024-10-01
100    6   Citra   86  Laki-Laki      Malang  15000000 2024-10-01
101   21    Nina   86  Perempuan  Yogyakarta  14000000 2024-10-01
102   36    Budi   86  Perempuan  Yogyakarta   9412594 2024-10-01

[103 rows x 7 columns]

In [ ]:
df['Gender'].unique()

array(['Laki-Laki', 'Perempuan'], dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        103 non-null    int64
 1   Name      103 non-null    object
 2   Age       103 non-null    Int64
 3   Gender    103 non-null    object
 4   City      103 non-null    object
 5   Salary    103 non-null    Int64
 6   JoinDate  103 non-null    datetime64[ns]
dtypes: Int64(2), datetime64[ns](1), int64(1), object(3)
memory usage: 6.0+ KB

In [21]:
# handle outlier umur diatas 100
# Mengganti umur di atas 100 dengan median umur
median_age = df['Age'][df['Age'] <= 100].median()
df['Age'] = df['Age'].apply(lambda x: median_age if x > 100 else x)

# Update juga untuk df_final jika sudah didefinisikan
if 'df_final' in globals():
    df_final = df.drop_duplicates()

df['Age'].unique()

array([86., 41., 51., 34., 26., 53., 54., 43., 55., 39., 31., 29., 28.,
       49., 27., 47., 45., 38.])

In [22]:
df.duplicated().sum()

np.int64(3)

In [23]:
df_final=df.drop_duplicates()
df_final

     ID    Name   Age     Gender        City    Salary   JoinDate
0     1    Dewi  86.0  Laki-Laki     Bandung   9412594 2024-10-01
1     2   Citra  86.0  Perempuan      Malang   8000000 2024-10-01
2     3   Indah  41.0  Perempuan     Bandung  13000000 2024-10-01
3     4   Sinta  86.0  Laki-Laki       Medan   9000000 2024-10-01
4     5  Hendra  86.0  Perempuan       Medan   9000000 2024-10-01
..  ...     ...   ...        ...         ...       ...        ...
95   96   Oscar  86.0  Perempuan     Bandung   9412594 2024-10-01
96   97    Budi  86.0  Perempuan    Semarang   8286905 2024-10-01
97   98    Nina  86.0  Perempuan  Yogyakarta   9412594 2024-10-01
98   99    Tono  38.0  Laki-Laki      Malang   9412594 2024-10-01
99  100    Nina  53.0  Laki-Laki      Malang   7000000 2024-10-01

[100 rows x 7 columns]

In [24]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        100 non-null    int64
 1   Name      100 non-null    object
 2   Age       100 non-null    float64
 3   Gender    100 non-null    object
 4   City      100 non-null    object
 5   Salary    100 non-null    Int64
 6   JoinDate  100 non-null    datetime64[ns]
dtypes: Int64(1), datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 6.3+ KB